version: '3'
services:
  # Postgres Service
  postgres:
    image: postgres:13.3
    restart: on-failure
    container_name: anemone_db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anemone
    networks:
      - anemone-network
    volumes:
      - anemone:/var/lib/postgresql/data
  # IOT Data
  dynamo:
    image: amazon/dynamodb-local:2.5.4
    container_name: anemone_dynamo
    ports:
      - 8888:8000
    volumes:
      - anemone-iot:/data
    networks:
      - anemone-network
  api:
    container_name: anemone_api
    image: tuanes/tangent-api:0.0.1
    restart: unless-stopped
    env_file:
      - ./.api.env
    ports:
      - 8000:80
    depends_on:
      - postgres
      - dynamo
    networks:
      - anemone-network
networks:
  anemone-network: {}
volumes:
  anemone: {}
  anemone-iot: {}
