version: '3'
services:
  pg-write:
    container_name: tangent-db
    image: 'bitnami/postgresql:15.2.0'
    restart: 'always'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '$POSTGRES_PORT:5432'
    networks:
      - tangent-network
  app:
    container_name: tangent-app
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    depends_on:
      - pg-write
    networks:
      - tangent-network

networks:
  tangent-network: {}
