version: '3'
services:
  pg-write:
    container_name: pg-write-company-db
    image: 'bitnami/postgresql:15.2.0'
    restart: 'always'
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - '$POSTGRES_PORT:5432'
